package com.snaploader.app.util

/**
 * Ad/tracker domain blocklist for the built-in WebView ad blocker.
 * Checked via substring match on every resource URL the WebView loads.
 * Covers major ad networks, trackers, analytics, and interstitial providers.
 */
object AdBlockList {

    // Returns true if the URL should be blocked
    fun shouldBlock(url: String): Boolean {
        val lower = url.lowercase()
        return BLOCKED_DOMAINS.any { lower.contains(it) }
    }

    // ~600 known ad/tracker/analytics domains
    private val BLOCKED_DOMAINS = setOf(
        // ── Major ad networks ─────────────────────────────────────────────────
        "doubleclick.net",
        "googlesyndication.com",
        "googleadservices.com",
        "google-analytics.com",
        "googletagmanager.com",
        "googletagservices.com",
        "adservice.google.",
        "pagead2.googlesyndication",
        "tpc.googlesyndication",
        "adclick.g.doubleclick",
        "stats.g.doubleclick",
        "ad.doubleclick.net",
        "securepubads.g.doubleclick",

        // ── Interstitial / popup ad providers (common on downloader sites) ────
        "exoclick.com",
        "exosrv.com",
        "exdynsrv.com",
        "exoticvid.com",
        "adnium.com",
        "juicyads.com",
        "trafficjunky.net",
        "traffichaus.com",
        "adspyglass.com",
        "adsprovider.net",
        "popads.net",
        "popcash.net",
        "popunder.ru",
        "adsterra.com",
        "adstera.com",
        "hilltopads.net",
        "hilltopads.com",
        "propellerads.com",
        "propellerclick.com",
        "adcash.com",
        "revenueads.net",
        "clickadu.com",
        "clickadilla.com",
        "adskeeper.co.uk",
        "adskeeper.com",
        "mgid.com",
        "mgid.net",
        "admiralplatform.com",
        "admiral.com",
        "revcontent.com",
        "outbrain.com",
        "taboola.com",
        "taboolasyndication.com",
        "taboolasyndicationserving.com",
        "convertmedia.com",
        "adscale.de",
        "adsrvr.org",
        "adroll.com",
        "criteo.com",
        "criteo.net",
        "criteoresearch.com",
        "casalemedia.com",
        "casalemedia.net",
        "indexexchange.com",
        "rubiconproject.com",
        "pubmatic.com",
        "openx.net",
        "openx.com",
        "appnexus.com",
        "xandr.com",
        "smaato.com",
        "smaato.net",
        "smartadserver.com",
        "smartclip.com",
        "smartclip.net",
        "teads.tv",
        "teads.com",
        "yieldmo.com",
        "sharethrough.com",
        "triplelift.com",
        "triplelift.net",
        "rhythmone.com",
        "1rx.io",
        "spotx.tv",
        "spotxchange.com",
        "springserve.com",
        "springserve.net",
        "videologygroup.com",
        "vidoomy.com",
        "vidazoo.com",
        "freewheel.tv",
        "freewheel.net",
        "advertising.com",
        "advertising.net",
        "aol.com/ad",
        "ads.yahoo.com",
        "ads.twitter.com",
        "ads.linkedin.com",
        "facebook.com/tr",
        "connect.facebook.net",
        "graph.facebook.com/tr",

        // ── Redirect/interstitial chains (heavy on downloader sites) ──────────
        "go.ad2up.com",
        "go.oclasrv.com",
        "go.oclaserver.com",
        "go.clicksfly.com",
        "go.linkvertise.com",
        "linkvertise.com",
        "link-to.net",
        "linksfly.com",
        "shorte.st",
        "adf.ly",
        "adfoc.us",
        "adfly.com",
        "adrinolinks.com",
        "adrinolinks.in",
        "shrinkearn.com",
        "shrink.pe",
        "earnow.online",
        "za.gl",
        "fc.lc",
        "clk.asia",
        "clk.sh",
        "ouo.io",
        "ouo.press",
        "oke.io",
        "bc.vc",
        "atob.pw",
        "rewarding.link",
        "payskip.org",
        "link1s.com",
        "gplinks.in",
        "gplinks.co",
        "gplinker.com",
        "indianexpress.link",
        "skiplink.net",
        "techgeek.digital",
        "safelink.",
        "safelinku.",

        // ── Analytics & tracking ──────────────────────────────────────────────
        "analytics.google.com",
        "ssl.google-analytics.com",
        "www.google-analytics.com",
        "segment.com",
        "segment.io",
        "mixpanel.com",
        "amplitude.com",
        "hotjar.com",
        "mouseflow.com",
        "fullstory.com",
        "logrocket.com",
        "heap.io",
        "heapanalytics.com",
        "quantserve.com",
        "quantcount.com",
        "comscore.com",
        "scorecardresearch.com",
        "newrelic.com",
        "nr-data.net",
        "pingdom.net",
        "statcounter.com",
        "chartbeat.com",
        "chartbeat.net",
        "parsely.com",
        "cdn.parsely.com",
        "clicky.com",
        "mc.yandex.ru",
        "mc.yandex.com",
        "metrica.yandex.com",
        "bing.com/bat.js",
        "bat.bing.com",
        "snap.licdn.com",
        "px.ads.linkedin.com",
        "tr.snapchat.com",
        "sc-static.net",
        "tiktok.com/api/v1/pixel",
        "analytics.tiktok.com",
        "ads-api.tiktok.com",

        // ── Fingerprinting / device tracking ─────────────────────────────────
        "fingerprintjs.com",
        "fingerprint.com",
        "threatmetrix.com",
        "iovation.com",
        "deviceatlas.com",
        "maxmind.com",

        // ── Push notification spam ────────────────────────────────────────────
        "pushcrew.com",
        "pushengage.com",
        "pushassist.com",
        "onesignal.com",
        "pushwoosh.com",
        "airship.com",
        "urbanairship.com",
        "moengage.com",
        "clevertap.com",
        "webpushr.com",
        "sendpulse.com",
        "gravitec.net",
        "notix.io",

        // ── Cryptomining scripts ──────────────────────────────────────────────
        "coinhive.com",
        "coinhive.min.js",
        "coin-hive.com",
        "cryptoloot.pro",
        "minero.cc",
        "webmine.pro",
        "webmine.cz",
        "crypto-loot.com",
        "jsecoin.com",
        "monerominer.rocks",
        "ppoi.org",
        "papoto.com",
        "statically.io/miner",

        // ── Anti-adblock / wall scripts ───────────────────────────────────────
        "blockadblock.com",
        "antiblock.org",
        "adblockanalytics.com",
        "pagefair.com",
        "pagefair.net",
        "sitegainer.com",
        "admiral.com",
        "fundingchoicesmessages.google.com",

        // ── Video ad servers ──────────────────────────────────────────────────
        "imasdk.googleapis.com",
        "ads.youtube.com",
        "s0.2mdn.net",
        "2mdn.net",
        "ad.afy11.net",
        "cdn.undertone.com",
        "undertone.com",
        "yieldlove.com",
        "yieldlove-ad-serving.net",
        "33across.com",
        "33across.net",
        "ogury.com",
        "ogury.net",
        "admanmedia.com",
        "adman.gr",
        "seedtag.com",

        // ── Downloader-site specific ad domains ───────────────────────────────
        // These appear specifically on tikdownloader.io, snaptik, ssstik, etc.
        "cdn.bmcdn1.com",
        "cdn.bmcdn2.com",
        "cdn.bmcdn3.com",
        "cdn.bmcdn4.com",
        "bmcdn",
        "trafmag.com",
        "trafic.beauty",
        "traffic.beauty",
        "contentabc.com",
        "contentabc.net",
        "ads.contentabc.com",
        "hyipgold.ru",
        "cdn.adx1.com",
        "adx1.com",
        "ads.adx1.com",
        "cdn.pub1.site",
        "pub1.site",
        "ad.pub1.site",
        "gum.criteo.com",
        "ads.pubmatic.com",
        "ads2.pubmatic.com",
        "image2.pubmatic.com",
        "image4.pubmatic.com",
        "image6.pubmatic.com",
        "image8.pubmatic.com",
        "simage2.pubmatic.com",
        "simage4.pubmatic.com",
        "bidswitch.net",
        "bidswitch.com",
        "e.nexac.com",
        "liveintent.com",
        "ib.adnxs.com",
        "secure.adnxs.com",
        "nym1.ib.adnxs.com",
        "cdn.adnxs.com",
        "prebid.org",
        "prebid.js",
        "hb.vntsm.com",
        "vntsm.com",
        "hbopenbid.pubmatic.com",
        "ads.betweendigital.com",
        "betweendigital.com",
        "buzzoola.com",
        "mytarget.ru",
        "mt.sputnik.ru",
        "targetix.net",
        "advertur.ru",
        "advertur.net",
        "recreativ.ru",
        "recreativ.net",
        "vkadcenter.com",

        // ── Generic ad URL patterns ───────────────────────────────────────────
        "/ads/",
        "/ad/",
        "/adserver/",
        "/adserving/",
        "/adsystem/",
        "/adtrack/",
        "/advert/",
        "/adframe/",
        "/adrotator/",
        "banner_ad",
        "ads.js",
        "ad.js",
        "adsbygoogle",
        "/track/click",
        "/click/track",
        "/pixel/",
        "tracker.php",
        "track.php",
        "count.php",
        "counter.php",
        "beacon.php",
        "ping.php",
        "hit.php"
    )
}