package com.shvertex.casinotoolspro.navigation

object Routes {
    const val HOME           = "home"
    const val STRATEGIES     = "strategies"
    const val DICE_SIM       = "dice_sim"
    const val DICE_CALC      = "dice_calc"
    const val MONTE_CARLO    = "monte_carlo"
    const val DICE_OPTIMIZER = "dice_optimizer"
    const val DICE_GENERATOR = "dice_generator"
    const val STRATEGY_FORGE = "strategy_forge"
    const val DICE_EVOLUTION = "dice_evolution"
    const val LIMBO_EVOLUTION= "limbo_evolution"
    const val KENO_EVOLUTION = "keno_evolution"
    const val MINES_EVOLUTION= "mines_evolution"
    const val STRESS_TEST    = "stress_test"
    const val BANKROLL_LAB   = "bankroll_lab"
    const val KENO_MC        = "keno_mc"
    const val MINES_ANALYTICS= "mines_analytics"
    const val BLACKJACK      = "blackjack"
    const val SPORTS_LAB     = "sports_lab"
    const val KELLY_CALC     = "kelly_calc"
    const val PARLAY         = "parlay"
    const val VALUE_BET      = "value_bet"
    const val ARBITRAGE      = "arbitrage"
    const val COMPOUND       = "compound"
    const val PATTERN        = "pattern"
    const val CONVERTER      = "converter"
    const val HISTORY        = "history"
}
